server:
    port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #API网关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
    url: jdbc:mysql://192.168.1.8:3306/gateway
    username: admin
    password: 123456
  application:
    name: ch-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    client:
      client-id: ChaoHua
      client-secret: secret
    resource:
      user-info-uri:  http://localhost:8084/auth/user
      prefer-token-info: true
#      loadBalanced: true
##############end#####################
####超时配置####
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  http:
#    client:
#      enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000
###超时配置###

logging:
  config: classpath:config/logback-test.xml
  path: logs/ch-gateway
  level:
    com.ch: debug
    org.springframework.cloud: debug