server:
    port: 7001

jasypt:
  encryptor:
    password: abc123
    algorithm: PBEWithMD5AndDES
spring:
  application:
    name: ch-gateway
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #API网关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.zhaohuajike.cn:3306/dev_ch_gateway
    username: admin
    password: ENC(hfO3JFDCY2HB6x+j1obZOg==)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          filters:
            - StripPrefix=1
      routes:
        - id: sso
          uri: lb://ch-sso
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: upms
          uri:  lb://ch-upms
          predicates:
            - Path=/upms/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true
#      loadBalanced: true
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  http:
    client:
      enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###

logging:
  config: classpath:config/logback-test.xml
  path: logs/ch-gateway
  level:
    com.ch: debug
    org.springframework.cloud: warn
    com.alibaba.nacos: warn
