server:
  port: 7001

jasypt:
  encryptor:
    password: abc123
#    algorithm: PBEWithMD5AndDES
spring:
  redis:
    ##
    jedis:
      pool:
        ### 连接池最大连接数（使用负值表示没有限制）
        max-active: 9
        ### 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ### 连接池中的最大空闲连接
        max-idle: 9
        ### 连接池中的最小空闲连接
        min-idle: 0
    ### 连接超时时间（毫秒）
    timeout: 60000
    ### Redis数据库索引(默认为0)
    host: 192.168.150.206
    port: 6379
    password: admin123
    database: 0
#    sentinel:
#      master: master
#      nodes:
#        - sentinel1:8001
#        - sentinel2:8001
#        - sentinel3:8001
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          filters:
            - StripPrefix=1
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
            series: SERVER_ERROR
#      loadBalanced: true
##############end#####################

# Cookie刷新配置
gateway:
  cookie:
    token-name: TOKEN
    max-age: 1800  # 30分钟
    refresh-threshold: 300  # 5分钟内过期时刷新
    path: /
    http-only: true
    secure: false  # 本地环境设为false，生产环境建议设为true
    auto-refresh: true
    enable-log: true
  
  # 请求记录配置
  request-recorder:
    enabled: true                    # 是否启用请求记录
    skip-urls:                       # 跳过的URL路径
      - "/upms/op/record/"
      - "/upms/login/record/"
      - "/health"
      - "/actuator/**"
    record-static-resources: false   # 是否记录静态资源请求
    record-websocket: false          # 是否记录WebSocket请求
    record-get-requests: true        # 是否记录GET请求
    timeout: 30000                   # 请求记录超时时间（毫秒）
    record-request-body: true        # 是否启用请求体记录
    record-response-body: true       # 是否启用响应体记录
    max-request-body-size: 1048576   # 请求体最大大小（字节）- 1MB
    max-response-body-size: 1048576  # 响应体最大大小（字节）- 1MB
    enable-sensitive-masking: true   # 是否启用敏感信息脱敏
    sensitive-fields:                # 敏感字段列表
      - "password"
      - "token"
      - "authorization"
      - "secret"
      - "key"

####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  http:
    client:
      enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###

logging:
#  config: classpath:config/logback-test.xml
  level:
    com.ch: debug
    org.springframework.cloud: info
    com.alibaba.nacos: warn
  file:
    path: logs/ch-gateway
rocketmq:
  enabled: false
  name-server: 192.168.0.206:9876 # 自己的RocketMQ服务地址
  producer:
    send-message-timeout: 300000
    group: ch-gateway


feign:
  httpclient:
    enabled: true