server:
    port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#API网关配置
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  #路由配置
  routes:
    auth:    #认证服务
      #响应的路径
      path: /auth/**
      #敏感头信息
      sensitiveHeaders:
      custom-sensitive-headers: true  #http://blog.didispace.com/spring-cloud-zuul-cookie-redirect/ zuul授权码跳转问题
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId:  ch-auth
      strip-prefix: false
    admin: #生产者服务
      #响应的路径
      path: /admin/**
      sensitiveHeaders:
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId:  ch-admin
    blog: #生产者服务
      #响应的路径
      path: /blog/**
      sensitiveHeaders:
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId:  ch-blog
      strip-prefix: false
  #添加代理头
  add-proxy-headers: true


security:
  oauth2:
    resource:
      user-info-uri:  http://localhost:8084/auth/user
      prefer-token-info: true
#      loadBalanced: true
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  http:
    client:
      enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000
###超时配置###

logging:
  config: classpath:conf/logback-test.xml
  path: logs/ch-gateway
  level:
    com.ch: debug
    org.springframework.cloud: debug